### PR TITLE
Added support for "hosted" and "sdk" dependencies

### LINKED ISSUE #1: HostedReference doesn't support self-hosted dependencies
When attempting to create a `Pubspec` instance from yaml that contains dependencies that are self-hosted, an error results:

```shell
Bad state: unexpected dependency type hosted
package:pubspec/src/dependency.dart 25:11  new DependencyReference.fromJson
package:pubspec/src/pubspec.dart 99:40     new PubSpec.fromJson.<fn>
package:stuff/src/json_utils.dart 122:45   JsonParser.mapValues.<fn>
dart:collection                            YamlNode&MapMixin.forEach
package:stuff/src/json_utils.dart 121:7    JsonParser.mapValues
package:pubspec/src/pubspec.dart 98:25     new PubSpec.fromJson
package:pubspec/src/pubspec.dart 108:11    new PubSpec.fromYamlString
```
Further digging suggests that the `HostedReference` class doesn't support the notion of packages being hosted on a server other than the global one.

This unit-test can be used to reproduce the issue:

```dart
@TestOn('vm')

import 'package:test/test.dart';
import 'package:pubspec/pubspec.dart';

void main() {
  test('that we can parse self hosted dependencies', () async {
    final pubspecString = 'name: my_test_lib\n'
        'version: 0.1.0\n'
        'description: for testing\n'
        'dependencies:\n'
        '    meta: ^1.0.0\n'
        '    self_hosted_lib:\n'
        '        hosted:\n'
        '            name: custom_lib\n'
        '            url: https://pub.mycompany.org\n'
        '            version: ^0.1.0';

    final p = new PubSpec.fromYamlString(pubspecString);
  });
}
```

### PR DESCRIPTION
**Pull request by thosakwe**
Resolves #1 and #2. Includes tests.

### CODE REVIEW

**Comment by thosakwe** [comment]
Hi, thanks for merging the PR! Would you be willing to publish a new version to Pub? Thanks.

**Comment by Andersmholmgren** [comment]
done. I'll need to figure out what to do about this and other packages I don't maintain any more

**Comment by thosakwe** [comment]
Thanks. I'm willing to help you maintain Dart packages, especially now that Dart is going through a lot of changes.

**Comment by Andersmholmgren** [comment]
Great. I don’t have much to do with dart these days I’m afraid. I’ll likely
create an org and transfer the repo there

**Comment by thosakwe** [comment]
Awesome, thank you. And thanks for all your contributions to the Dart
community over the years.

**Pull request merged**
